### ISSUE TITLE
Questions re applicability in fully distributed settings

### ISSUE THREAD

**Issue by kim** [dhuseby/did-git-spec#26]
Hello,

I came across DIDs only recently, so forgive if any of the following is a result of me not yet fully understanding the concept. We are building a p2p network for code collaboration over at [monadic](https://monadic.xyz), and - unsurprisingly - are facing some of the same challenges wrt identity management. It would be great to tap into DIDs, and also `git-did`, yet it seems like some of the assumptions made in the current version of the spec wouldn't quite work in a fully distributed setting. Hence a few questions:

* Is the `service` of type `git` supposed to be an example only (that is, service endpoints of any `type` could be used)? IOW, what if there is no canonical URI for a repo, because the development process of the project is fully distributed?
* Are there more specific ideas around what the `governance.{md,json}` should specify? I'm thinking that this would also tie into what's been said in #7. 

  What we came up with so far is to device a verification procedure very similar to [TUF](https://github.com/theupdateframework/specification/blob/master/tuf-spec.md#5-detailed-workflows), where the history of the repo identity must be followed from the initial revision up to the most recent one, checking attestation by a quorum of the maintainers at each revision along the way. That has some nice properties to defend against history rewrites and censorship, but poses another challenge in a fully distributed setting: it should be possible to perform this verification _before_ cloning the entire, potentially large, history of the repo from one or more untrusted sources. Since `git` doesn't allow partial checkouts, we devise storing metadata in disjoint branches, such that an upper bound on the data that has to be fetched can be guaranteed.

Would love to get your thoughts on this!

**Comment by twshelton** [comment]
Kim,

It's been a while since the initial discussions that got this repo started but I'll try to provide some context and hopefully answers to your questions.

Our original goals were to make it easy for developers to sign commits and then require that all commits be signed.  With this in place we could then start looking at ways to automate the auditing of projects for compliance with a specific license and other organizational legal requirements.

This could work in an environment without canonical URI's but creating one would make it easier for all interested developers to verify.  So for example one could register an identity using any of the DID methods and include that in the governance documents.

@dhuseby would be much better able to get into the details about using TUF.

There is active work being done on this in the form of a porcelain command to support the governance of the project.

I'd be happy to discuss further if you'd like.

Cheers,
Thomas

**Comment by kim** [comment]
@twshelton Thanks for the explanations, and sorry for the long delay. 

> This could work in an environment without canonical URI's

I'm not really convinced of this -- unless I'm misunderstanding something, establishing `git` as a DID method entails that there exists a canonical tree, and that it needs to be secured against history rewrites. Otherwise, the validity of the DID statements within a (copy of the) repos must be verified against an external system.

Anyways, we concluded that while similar in spirit, `did-git` doesn't fully apply to what we're trying to do, for a variety of reasons. If you're interested, some context can be found [here](https://radicle.community/t/about-identities/97).

I'm closing this now, but will keep watching how the spec evolves. Perhaps some convergence will emerge in the future.
